### ISSUE TITLE
Usage problem when using the Default profile

### ISSUE THREAD

**Issue by rsm-gh** [rsm-gh/alienware-kbl#12]
When no theme has been created and the user uses the `Default` profile it seems to be some problems. For example, if the user modifies the theme and then it try to apply the changes they are not being applied to the computer lights.

This seems to be a bug of the configuration file:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/alienware-kbl/GUI.py", line 689, in ILUMINATE_keyboard
    os.utime(self.configuration.path, None)
PermissionError: [Errno 13] Permission denied
```

**Comment by rsm-gh** [comment]
duplicated of #1
