### ISSUE TITLE
AttributeError: module 'Computers' has no attribute 'Alienware 15'

### ISSUE THREAD

**Issue by geekyJock8** [rsm-gh/alienware-kbl#23]
I'm able to access alienware-kbl from the terminal and through python scripts. But when I try to run it from the terminal by entering "alienware-kbl". It shows the following error:
```
(GUI.py:2630): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(GUI.py:2630): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(GUI.py:2630): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(GUI.py:2630): Gtk-WARNING **: Unknown type < define a new column > specified in treemodel liststore_default_blocks

(GUI.py:2630): Gtk-WARNING **: gtkliststore.c:516: Invalid type (null)
Traceback (most recent call last):
  File "/usr/share/alienware-kbl/GUI.py", line 1080, in <module>
    gui = GUI()
  File "/usr/share/alienware-kbl/GUI.py", line 306, in __init__
    self.computer = getattr(Computers, computer_name)()
AttributeError: module 'Computers' has no attribute 'Alienware 15'
```

I'm using **Alienware 15** (A06) and running _KDE Plasma 5.9.4 (Qt 5.8.0)_ on **Manjaro Linux**(_Kernel: 4.9.24-1-MANJARO x86_64_)

**Comment by rsm-gh** [comment]
I just comited the fix, does it works now?

**Comment by geekyJock8** [comment]
I don't if I'm doing something wrong but I first uninstalled the old version. Then downloaded the current one but now when execute _sudo ./setup_
It says _sudo: ./setup: command not found_

**Comment by rsm-gh** [comment]
You are probably not executing the command at the installation folder. If you do an `ls -la` you should see the `setup` file.

**Comment by geekyJock8** [comment]
![image](https://cloud.githubusercontent.com/assets/19239291/26149227/1fa229a2-3b17-11e7-84fc-8a5f6aec7da9.png)
I'm in the installation folder.
