### ISSUE TITLE
Add support to the Alienware 17 R4 computer

### ISSUE THREAD

**Issue by mgruben** [rsm-gh/alienware-kbl#29]
Running Arch Linux 4.11.9-1

```
 Dected As: Alienware15R3
 Vendor ID: 6268
 Product ID: 1328

DEVICE ID 187c:0530 on Bus 001 Address 004 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :    0x2 USB 0.02
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :   0x40 (64 bytes)
 idVendor               : 0x187c
 idProduct              : 0x0530
 bcdDevice              :    0x0 Device 0.0
 iManufacturer          :    0x1 Alienware
 iProduct               :    0x2 AW1517
 iSerialNumber          :    0x3 02.90
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 0 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x29 (41 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xe0 Self Powered, Remote Wakeup
   bMaxPower            :    0x0 (0 mA)
    INTERFACE 0: Human Interface Device ====================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x1
     bInterfaceClass    :    0x3 Human Interface Device
     bInterfaceSubClass :    0x0
     bInterfaceProtocol :    0x0
     iInterface         :    0x0 
      ENDPOINT 0x81: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :    0xa (10 bytes)
       bInterval        :    0xa
```
When attempting to Apply changes, the following stack trace results:

```
(GUI.py:22865): Gtk-WARNING **: Unknown type < define a new column > specified in treemodel liststore_default_blocks

(GUI.py:22865): Gtk-WARNING **: gtkliststore.c:516: Invalid type (null)

(GUI.py:22865): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=c48c0bf41a1443f9977435d5e18c4e25 --binary-syntax --close-stderr”: Child process exited with code 1

(GUI.py:22865): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=c48c0bf41a1443f9977435d5e18c4e25 --binary-syntax --close-stderr”: Child process exited with code 1

(GUI.py:22865): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=c48c0bf41a1443f9977435d5e18c4e25 --binary-syntax --close-stderr”: Child process exited with code 1

(GUI.py:22865): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=c48c0bf41a1443f9977435d5e18c4e25 --binary-syntax --close-stderr”: Child process exited with code 1
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/alienware-kbl/GUI.py", line 808, in ILUMINATE_keyboard
    self.controller.Write_Conf()
  File "/usr/share/alienware-kbl/Engine.py", line 195, in Write_Conf
    self.WaitForOk()
  File "/usr/share/alienware-kbl/Engine.py", line 282, in WaitForOk
    self.Get_State()
  File "/usr/share/alienware-kbl/Engine.py", line 298, in Get_State
    msg = self.driver.ReadDevice(request)
  File "/usr/share/alienware-kbl/Engine.py", line 135, in ReadDevice
    msg[0].packet))
  File "/usr/lib/python3.6/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow
```

**Comment by rsm-gh** [comment]
If the computer was detected its strange that you can not apply any change. Have you tried using the block testing window?

**Comment by mgruben** [comment]
I have; so long as I haven't tried to apply, I am able to connect to the device, as shown below:
![connect](https://user-images.githubusercontent.com/6686712/28944418-47d9434c-7857-11e7-9737-003d7b7b7745.png)

The warning on the window is sufficiently frightening, and my knowledge of this USB interface sufficiently small, that I haven't used the "TEST BLOCK" button.

However, if I use the "Lights Off" button, an overflow results:
```
Traceback (most recent call last):
  File "/usr/share/alienware-kbl/GUI.py", line 1207, in on_button_block_testing_lights_off_clicked
    self.testing_driver.computer.RESET_ALL_LIGHTS_OFF)
  File "/usr/share/alienware-kbl/Engine.py", line 307, in Reset
    msg = self.driver.ReadDevice(request)
  File "/usr/share/alienware-kbl/Engine.py", line 135, in ReadDevice
    msg[0].packet))
  File "/usr/lib/python3.6/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow
```

After an overflow, it would appear that `alienware-kbl` can no longer communicate with the device, until `alienware-kbl` is restarted.
Subsequent presses of the "Lights Off" button yields the following:
```
Traceback (most recent call last):
  File "/usr/share/alienware-kbl/GUI.py", line 1207, in on_button_block_testing_lights_off_clicked
    self.testing_driver.computer.RESET_ALL_LIGHTS_OFF)
  File "/usr/share/alienware-kbl/Engine.py", line 307, in Reset
    msg = self.driver.ReadDevice(request)
  File "/usr/share/alienware-kbl/Engine.py", line 135, in ReadDevice
    msg[0].packet))
  File "/usr/lib/python3.6/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow

Traceback (most recent call last):
  File "/usr/share/alienware-kbl/Engine.py", line 141, in Take_over
    self.dev.set_configuration()
  File "/usr/lib/python3.6/site-packages/usb/core.py", line 869, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/usb/core.py", line 148, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 794, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/alienware-kbl/GUI.py", line 1207, in on_button_block_testing_lights_off_clicked
    self.testing_driver.computer.RESET_ALL_LIGHTS_OFF)
  File "/usr/share/alienware-kbl/Engine.py", line 302, in Reset
    self.driver.Take_over()
  File "/usr/share/alienware-kbl/Engine.py", line 143, in Take_over
    self.dev.detach_kernel_driver(0)
  File "/usr/lib/python3.6/site-packages/usb/core.py", line 1077, in detach_kernel_driver
    interface)
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 902, in detach_kernel_driver
    _check(self.lib.libusb_detach_kernel_driver(dev_handle.handle, intf))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found
```

**Comment by rsm-gh** [comment]
Don't take the warning so serious, I played a lot with that interface and I never had problems. I just added the message as a disclaimer in case someone actually messes up his computer...

You can try the block testing button but I'm pretty sure that you will have the same problem. Its seems to be some kind of python-usb  error and sadly that' s the part of the code that I know the less.

If I have any clue I' ll try to help you but I almost never solve that kind problems. If you want to try to fix it I' d advice you to start by trying to change [the library used for the libusbpatch](https://github.com/rsm-gh/alienware-kbl/blob/stable/usr/bin/alienware-kbl).

**Comment by mgruben** [comment]
I tried commenting out the LD_PRELOAD line, and still got the same error.  
I then moved `libusb-1.0.so.0` to `libusb-1.0.so.0.orig`, and created a symlink so that `libusb-1.0.so.0 -> /usr/lib/libusb-1.0.so.0.1.0` (from Arch Linux), but still the error was the same.

I'm currently trying to read from and write to the device using `pyusb` directly, but whenever I try to `read` from the endpoint, I get this error:  
```python
>>> endp.read(0x0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/lib/python3.6/site-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 851, in intr_read
    timeout)
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
```

**Comment by rsm-gh** [comment]
Actually removing the `LD_PRELOAD` wont help you but I've seen that using some other libusb libs may do the trick. Take a [look to this](https://github.com/rsm-gh/alienware-kbl/issues/17#issuecomment-287372554) it may help you :)

**Comment by mgruben** [comment]
Taking a queue from that thread, I've updated `Computer.py` so that `DATA_LENGTH = 12`, rather than `9` as it was previously.

This fixes the `[Errno 75] Overflow` error, but I'm still getting `[Errno 16] Resource busy` and `[Errno 2] Entity not found`.

I haven't figured out how to point `alienware-kbl` to the git version of [`libusb`](https://github.com/libusb/libusb), but that is another possible path forward, as you suggest.

**Comment by rsm-gh** [comment]
I hope you find a solution since that's something that I can't do! Good luck and if you make any improvement please keep me updated, it may be a good contributions for many users :)

**Comment by mgruben** [comment]
Most of my progress thus far has been with [AlienFXLite](https://github.com/bchretien/AlienFxLite/issues/8#issuecomment-322572437).

Enough is different between the byte-structure assumptions for the M17xR4 and the 17 R4 that there are lots of quirks in communicating:
* pulse / morph speed (sometimes it listens, sometimes it doesn't)
* colors (I'm sure the addressing is off; I can't get any blue unless I specify a morph, and then the blue value is taken from the second-specified color
* regions (one of my media bars doesn't ever light up, and some regions only respond when other regions are also selected).

I think these codes are probably something that would require re-surveying the USB codes that are sent from AlienFX in a Windows Operating system.

**Comment by mgruben** [comment]
So I booted into the Windows via VirtualBox and the external 2.5" HDD that came with the laptop, and I installed [USBpcab](http://desowin.org/usbpcap/) to intercept some instructions to the AlienFX board.

I made a [repo for my WireShark packet captures](https://github.com/mgruben/AlienFXCaptures), which contains packet captures for all 12 zones, the power button, and the left media buttons, for:

1. Solid color changes, R-G-B,
2. Morph color changes, R-G-Blue-Black for first and second colors, and
3. Pulse color changes (all Blue), for each tempo from 0.1s to 1.0s

Unfortunately, I'm not enough of a USB wizard to know how to use them to write an `Alienware17R4` class for [Computers.py](https://github.com/rsm-gh/alienware-kbl/blob/stable/usr/share/alienware-kbl/Computers.py).

**Comment by rsm-gh** [comment]
I actually think that your problems are because of the libusb patch. When that patch doesn't works the `[Errno 16] Resource busy` and `[Errno 2] Entity not found` appear.

Sadly I've decreased at 99% my programming time but probably after coding the new release of the software I'll take a good look to `python-usb` because I think that the patch may be improved.

**Comment by rsm-gh** [comment]
I ignore why or when did the configuration disappeared from AKBL, but I just re-added it: [Configuration added for the Alienware M17 R4 ](https://github.com/rsm-gh/akbl/commit/89ffbd4231cfebdc889df143756d674ed5fb4fbb)
