### ISSUE TITLE
USB error 75 Overflow on Kubuntu 17.10, Alienware 15 R3

### ISSUE THREAD

**Issue by butla** [rsm-gh/alienware-kbl#39]
# System information

+ Distribution name: Kubuntu
+ Distribution version: 17.10
+ Python version: 3.6.3
+ Computer model: Alienware 15 R3
+ Output of the command `alienware-kbl --daemon-is-on`: True

# Bug description
I see the below error in the application's output when trying to perform actions:
```
ERROR from `/usr/share/AlienwareKBL/Bindings.py` on method `_command`:
Command=set_lights, arguments=[root,True]
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/Bindings.py", line 54, in _command
    response = getattr(self._pyro, command)(*args)
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 186, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 461, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "/usr/lib/python3/dist-packages/Pyro4/util.py", line 170, in deserializeData
    return self.loads(data)
  File "/usr/lib/python3/dist-packages/Pyro4/util.py", line 558, in loads
    return self.recreate_classes(serpent.loads(data))
  File "/usr/lib/python3/dist-packages/Pyro4/util.py", line 411, in recreate_classes
    return self.dict_to_class(literal)
  File "/usr/lib/python3/dist-packages/Pyro4/util.py", line 575, in dict_to_class
    return super(SerpentSerializer, cls).dict_to_class(data)
  File "/usr/lib/python3/dist-packages/Pyro4/util.py", line 390, in dict_to_class
    raise errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: usb.core.USBError
```
Of course, nothing happens with the lights.

From the above error I deducted that the problem is because of an inner problem with USB.

I ran block-testing, clicked connect (a lot of output appeared in the application's output in the terminal, but they didn't seem like errors), then I pressed "lights off" and saw this stacktrace in the application's GUI window:
```
[Device found]: Vendor ID: 6268	 Product ID: 1328

Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/ADDONS/BlockTesting/BlockTesting.py", line 335, in on_button_block_testing_lights_off_clicked
    self._testing_controller.add_reset_line(self._computer.RESET_ALL_LIGHTS_OFF)
  File "/usr/share/AlienwareKBL/Engine/Core/Controller.py", line 77, in add_reset_line
    while not self._device_is_ready():
  File "/usr/share/AlienwareKBL/Engine/Core/Controller.py", line 48, in _device_is_ready
    msg = self._driver.read_device(constructor)
  File "/usr/share/AlienwareKBL/Engine/Core/Driver.py", line 107, in read_device
    msg = self._device.ctrl_transfer(self.READ_REQUEST_TYPE, self.READ_REQUEST, self.READ_VALUE, self.READ_INDEX, len(msg[0].packet))
  File "/usr/lib/python3/dist-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow
```
I'd be happy to provide more info and do debugging.

**Comment by butla** [comment]
Huh, this is probably a duplicate of #8, so I'm closing it.
