### ISSUE TITLE
Unable to use because of Pyro4 is unavailable

### ISSUE THREAD

**Issue by diveyez** [rsm-gh/alienware-kbl#41]
# System information

+ Distribution name: Debian 0
+ Distribution version: Current Stable
+ Python version: 3
+ Computer model: Alienware 17 R2
+ Output of the command `alienware-kbl --daemon-is-on`:
root@alienware:/home/diveyez# alienware-kbl --daemon-is-on
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/ADDONS/DefaultArguments.py", line 26, in <module>
    from Bindings import Bindings
  File "/usr/share/AlienwareKBL/Bindings.py", line 22, in <module>
    import Pyro4
ImportError: No module named 'Pyro4'

# Bug description
root@alienware:/home/diveyez# alienware-kbl --start-indicator
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/ADDONS/Indicator/Indicator.py", line 28, in <module>
    import Pyro4
ImportError: No module named 'Pyro4'

**Comment by rsm-gh** [comment]
Hi, that's normal, you must install Pyro4. It appears at the installation instructions.
